"""Add response field to tickets

Revision ID: 68456b1097a5
Revises: 7024fa15fcac
Create Date: 2026-02-26 08:39:49.921814

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '68456b1097a5'
down_revision: Union[str, Sequence[str], None] = '7024fa15fcac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tickets', sa.Column('response', sa.Text(), nullable=True))
    op.alter_column('users', 'role',
               existing_type=postgresql.ENUM('USER', 'OPERATOR', 'ADMIN', name='userrole'),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'role',
               existing_type=postgresql.ENUM('USER', 'OPERATOR', 'ADMIN', name='userrole'),
               nullable=True)
    op.drop_column('tickets', 'response')
    # ### end Alembic commands ###
